# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'massons.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import pyqtSignal, QObject, Qt, QThread
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QPixmap

import threading
import time

import _game
import _time

class ThreadClass(QThread):
        any_signal = QtCore.pyqtSignal(int)
        def __init__(self, parent = None):
                super(ThreadClass, self).__init__(parent)
                self.is_running = True
        def run(self):
                while True:
                        self.any_signal.emit(1)
                        time.sleep(0.1)
        def stop(self):
                self.is_running = False
                self.terminate()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon('img/massons.ico'))
        MainWindow.resize(1200, 720)
        MainWindow.setMaximumSize(QtCore.QSize(1200, 720))
        MainWindow.setMinimumSize(QtCore.QSize(775, 500))
        MainWindow.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        pixmap = QPixmap("img/red.jpg")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, 50, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.runImg = QtWidgets.QLabel(self.centralwidget)
        runl = QtWidgets.QHBoxLayout(self.runImg)
        self.run = QtWidgets.QLabel(self.runImg)
        runl.addWidget(self.run)
        self.runImg.setMinimumSize(QtCore.QSize(200, 25))
        self.runImg.setMaximumSize(QtCore.QSize(400, 50))
        self.run.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.runImg.setPixmap(pixmap)
        self.runImg.setScaledContents(True)
        self.run.setAlignment(QtCore.Qt.AlignCenter)
        self.run.setObjectName("run")
        self.verticalLayout.addWidget(self.runImg)
        self.doorImg = QtWidgets.QLabel(self.centralwidget)
        self.doorImg.setPixmap(pixmap)
        self.doorImg.setScaledContents(True)
        self.door = QtWidgets.QLabel(self.doorImg)
        doorl = QtWidgets.QHBoxLayout(self.doorImg)
        doorl.addWidget(self.door)
        self.doorImg.setMinimumSize(QtCore.QSize(200, 25))
        self.doorImg.setMaximumSize(QtCore.QSize(400, 50))
        self.door.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.door.setAlignment(QtCore.Qt.AlignCenter)
        self.doorImg.setObjectName("door")
        self.verticalLayout.addWidget(self.doorImg)
        self.bookImg = QtWidgets.QLabel(self.centralwidget)
        self.bookImg.setPixmap(pixmap)
        self.bookImg.setScaledContents(True)
        self.book = QtWidgets.QLabel(self.bookImg)
        bookl = QtWidgets.QHBoxLayout(self.bookImg)
        bookl.addWidget(self.book)
        self.bookImg.setMinimumSize(QtCore.QSize(200, 25))
        self.bookImg.setMaximumSize(QtCore.QSize(400, 50))
        self.book.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.book.setAlignment(QtCore.Qt.AlignCenter)
        self.bookImg.setObjectName("book")
        self.verticalLayout.addWidget(self.bookImg)
        self.coinImg = QtWidgets.QLabel(self.centralwidget)
        self.coinImg.setPixmap(pixmap)
        self.coinImg.setScaledContents(True)
        self.coin = QtWidgets.QLabel(self.coinImg)
        coinl = QtWidgets.QHBoxLayout(self.coinImg)
        coinl.addWidget(self.coin)
        self.coinImg.setMinimumSize(QtCore.QSize(200, 25))
        self.coinImg.setMaximumSize(QtCore.QSize(400, 50))
        self.coin.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.coin.setAlignment(QtCore.Qt.AlignCenter)
        self.coinImg.setObjectName("coin")
        self.verticalLayout.addWidget(self.coinImg)
        self.declarationImg = QtWidgets.QLabel(self.centralwidget)
        self.declarationImg.setPixmap(pixmap)
        self.declarationImg.setScaledContents(True)
        self.declaration = QtWidgets.QLabel(self.declarationImg)
        declarationl = QtWidgets.QHBoxLayout(self.declarationImg)
        declarationl.addWidget(self.declaration)
        self.declarationImg.setMinimumSize(QtCore.QSize(200, 25))
        self.declarationImg.setMaximumSize(QtCore.QSize(400, 50))
        self.declaration.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.declaration.setAlignment(QtCore.Qt.AlignCenter)
        self.declarationImg.setObjectName("declaration")
        self.verticalLayout.addWidget(self.declarationImg)
        self.brickImg = QtWidgets.QLabel(self.centralwidget)
        self.brickImg.setPixmap(pixmap)
        self.brickImg.setScaledContents(True)
        self.brick = QtWidgets.QLabel(self.brickImg)
        brickl = QtWidgets.QHBoxLayout(self.brickImg)
        brickl.addWidget(self.brick)
        self.brickImg.setMinimumSize(QtCore.QSize(200, 25))
        self.brickImg.setMaximumSize(QtCore.QSize(400, 50))
        self.brick.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.brick.setAlignment(QtCore.Qt.AlignCenter)
        self.brickImg.setObjectName("brick")
        self.verticalLayout.addWidget(self.brickImg)
        self.handImg = QtWidgets.QLabel(self.centralwidget)
        self.handImg.setPixmap(pixmap)
        self.handImg.setScaledContents(True)
        self.hand = QtWidgets.QLabel(self.handImg)
        handl = QtWidgets.QHBoxLayout(self.handImg)
        handl.addWidget(self.hand)
        self.handImg.setMinimumSize(QtCore.QSize(200, 25))
        self.handImg.setMaximumSize(QtCore.QSize(400, 50))
        self.hand.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.hand.setAlignment(QtCore.Qt.AlignCenter)
        self.handImg.setObjectName("hand")
        self.verticalLayout.addWidget(self.handImg)
        self.cupImg = QtWidgets.QLabel(self.centralwidget)
        self.cupImg.setPixmap(pixmap)
        self.cupImg.setScaledContents(True)
        self.cup = QtWidgets.QLabel(self.cupImg)
        cupl = QtWidgets.QHBoxLayout(self.cupImg)
        cupl.addWidget(self.cup)
        self.cupImg.setMinimumSize(QtCore.QSize(200, 25))
        self.cupImg.setMaximumSize(QtCore.QSize(400, 50))
        self.cup.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.cup.setAlignment(QtCore.Qt.AlignCenter)
        self.cupImg.setObjectName("cup")
        self.verticalLayout.addWidget(self.cupImg)
        self.tableImg = QtWidgets.QLabel(self.centralwidget)
        self.tableImg.setPixmap(pixmap)
        self.tableImg.setScaledContents(True)
        self.table = QtWidgets.QLabel(self.tableImg)
        tablel = QtWidgets.QHBoxLayout(self.tableImg)
        tablel.addWidget(self.table)
        self.tableImg.setMinimumSize(QtCore.QSize(200, 25))
        self.tableImg.setMaximumSize(QtCore.QSize(400, 50))
        self.table.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.table.setAlignment(QtCore.Qt.AlignCenter)
        self.tableImg.setObjectName("table")
        self.verticalLayout.addWidget(self.tableImg)
        self.presidentImg = QtWidgets.QLabel(self.centralwidget)
        self.presidentImg.setPixmap(pixmap)
        self.presidentImg.setScaledContents(True)
        self.president = QtWidgets.QLabel(self.presidentImg)
        presidentl = QtWidgets.QHBoxLayout(self.presidentImg)
        presidentl.addWidget(self.president)
        self.presidentImg.setMinimumSize(QtCore.QSize(200, 25))
        self.presidentImg.setMaximumSize(QtCore.QSize(400, 50))
        self.president.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.president.setAlignment(QtCore.Qt.AlignCenter)
        self.presidentImg.setObjectName("president")
        self.verticalLayout.addWidget(self.presidentImg)
        self.ringImg = QtWidgets.QLabel(self.centralwidget)
        self.ringImg.setPixmap(pixmap)
        self.ringImg.setScaledContents(True)
        self.ring = QtWidgets.QLabel(self.ringImg)
        ringl = QtWidgets.QHBoxLayout(self.ringImg)
        ringl.addWidget(self.ring)
        self.ringImg.setMinimumSize(QtCore.QSize(200, 25))
        self.ringImg.setMaximumSize(QtCore.QSize(400, 50))
        self.ring.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.ring.setAlignment(QtCore.Qt.AlignCenter)
        self.ringImg.setObjectName("ring")
        self.verticalLayout.addWidget(self.ringImg)
        self.playersImg = QtWidgets.QLabel(self.centralwidget)
        self.playersImg.setPixmap(pixmap)
        self.playersImg.setScaledContents(True)
        self.players = QtWidgets.QLabel(self.playersImg)
        playersl = QtWidgets.QHBoxLayout(self.playersImg)
        playersl.addWidget(self.players)
        self.playersImg.setMinimumSize(QtCore.QSize(200, 25))
        self.playersImg.setMaximumSize(QtCore.QSize(400, 50))
        self.players.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.players.setAlignment(QtCore.Qt.AlignCenter)
        self.playersImg.setObjectName("players")
        self.verticalLayout.addWidget(self.playersImg)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bt_init = QtWidgets.QPushButton(self.centralwidget)
        self.bt_init.setMinimumSize(QtCore.QSize(105, 25))
        self.bt_init.setMaximumSize(QtCore.QSize(210, 50))
        self.bt_init.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.bt_init.setObjectName("bt_init")
        self.horizontalLayout_4.addWidget(self.bt_init)
        self.quest_state = QtWidgets.QLabel(self.centralwidget)
        self.quest_state.setMinimumSize(QtCore.QSize(105, 26))
        self.quest_state.setMaximumSize(QtCore.QSize(210, 50))
        self.quest_state.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.quest_state.setAlignment(QtCore.Qt.AlignCenter)
        self.quest_state.setObjectName("quest_state")
        self.horizontalLayout_4.addWidget(self.quest_state)
        self.bt_run = QtWidgets.QPushButton(self.centralwidget)
        self.bt_run.setMinimumSize(QtCore.QSize(105, 25))
        self.bt_run.setMaximumSize(QtCore.QSize(210, 50))
        self.bt_run.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.bt_run.setObjectName("bt_run")
        self.horizontalLayout_4.addWidget(self.bt_run)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setMinimumSize(QtCore.QSize(105, 15))
        self.label_15.setMaximumSize(QtCore.QSize(210, 30))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bt_hallwayOn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_hallwayOn.setMinimumSize(QtCore.QSize(50, 20))
        self.bt_hallwayOn.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_hallwayOn.setObjectName("bt_hallwayOn")
        self.horizontalLayout_6.addWidget(self.bt_hallwayOn)
        self.bt_hallwayOff = QtWidgets.QPushButton(self.centralwidget)
        self.bt_hallwayOff.setMinimumSize(QtCore.QSize(50, 20))
        self.bt_hallwayOff.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_hallwayOff.setObjectName("bt_hallwayOff")
        self.horizontalLayout_6.addWidget(self.bt_hallwayOff)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setMinimumSize(QtCore.QSize(105, 15))
        self.label_16.setMaximumSize(QtCore.QSize(210, 30))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_11.addWidget(self.label_16)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.bt_room1On = QtWidgets.QPushButton(self.centralwidget)
        self.bt_room1On.setMinimumSize(QtCore.QSize(50, 20))
        self.bt_room1On.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_room1On.setObjectName("bt_room1On")
        self.horizontalLayout_12.addWidget(self.bt_room1On)
        self.bt_room1Off = QtWidgets.QPushButton(self.centralwidget)
        self.bt_room1Off.setMinimumSize(QtCore.QSize(50, 20))
        self.bt_room1Off.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_room1Off.setObjectName("bt_room1Off")
        self.horizontalLayout_12.addWidget(self.bt_room1Off)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11.addLayout(self.verticalLayout_11)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setMinimumSize(QtCore.QSize(105, 15))
        self.label_14.setMaximumSize(QtCore.QSize(210, 30))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bt_coinOn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_coinOn.setMinimumSize(QtCore.QSize(50, 20))
        self.bt_coinOn.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_coinOn.setObjectName("bt_coinOn")
        self.horizontalLayout_5.addWidget(self.bt_coinOn)
        self.bt_coinOff = QtWidgets.QPushButton(self.centralwidget)
        self.bt_coinOff.setMinimumSize(QtCore.QSize(50, 20))
        self.bt_coinOff.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_coinOff.setObjectName("bt_coinOff")
        self.horizontalLayout_5.addWidget(self.bt_coinOff)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setMaximumSize(QtCore.QSize(210, 30))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_14.addWidget(self.label_17)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.bt_declarationOn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_declarationOn.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_declarationOn.setObjectName("bt_declarationOn")
        self.horizontalLayout_13.addWidget(self.bt_declarationOn)
        self.bt_declarationOff = QtWidgets.QPushButton(self.centralwidget)
        self.bt_declarationOff.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_declarationOff.setObjectName("bt_declarationOff")
        self.horizontalLayout_13.addWidget(self.bt_declarationOff)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setMaximumSize(QtCore.QSize(210, 30))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_13.addWidget(self.label_18)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.bt_brickOn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_brickOn.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_brickOn.setObjectName("bt_brickOn")
        self.horizontalLayout_14.addWidget(self.bt_brickOn)
        self.bt_brickOff = QtWidgets.QPushButton(self.centralwidget)
        self.bt_brickOff.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_brickOff.setObjectName("bt_brickOff")
        self.horizontalLayout_14.addWidget(self.bt_brickOff)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setMaximumSize(QtCore.QSize(210, 30))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_12.addWidget(self.label_19)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.bt_stoneOn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_stoneOn.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_stoneOn.setObjectName("bt_stoneOn")
        self.horizontalLayout_15.addWidget(self.bt_stoneOn)
        self.bt_stoneOff = QtWidgets.QPushButton(self.centralwidget)
        self.bt_stoneOff.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_stoneOff.setObjectName("bt_stoneOff")
        self.horizontalLayout_15.addWidget(self.bt_stoneOff)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_10.addLayout(self.verticalLayout_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setMaximumSize(QtCore.QSize(210, 30))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_17.addWidget(self.label_20)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.bt_room2On = QtWidgets.QPushButton(self.centralwidget)
        self.bt_room2On.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_room2On.setObjectName("bt_room2On")
        self.horizontalLayout_16.addWidget(self.bt_room2On)
        self.bt_room2Off = QtWidgets.QPushButton(self.centralwidget)
        self.bt_room2Off.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_room2Off.setObjectName("bt_room2Off")
        self.horizontalLayout_16.addWidget(self.bt_room2Off)
        self.verticalLayout_17.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9.addLayout(self.verticalLayout_17)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setMaximumSize(QtCore.QSize(210, 30))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_16.addWidget(self.label_21)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.bt_leftOn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_leftOn.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_leftOn.setObjectName("bt_leftOn")
        self.horizontalLayout_17.addWidget(self.bt_leftOn)
        self.bt_leftOff = QtWidgets.QPushButton(self.centralwidget)
        self.bt_leftOff.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_leftOff.setObjectName("bt_leftOff")
        self.horizontalLayout_17.addWidget(self.bt_leftOff)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_9.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setMaximumSize(QtCore.QSize(210, 30))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_15.addWidget(self.label_22)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.bt_tableOn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_tableOn.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_tableOn.setObjectName("bt_tableOn")
        self.horizontalLayout_18.addWidget(self.bt_tableOn)
        self.bt_tableOff = QtWidgets.QPushButton(self.centralwidget)
        self.bt_tableOff.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_tableOff.setObjectName("bt_tableOff")
        self.horizontalLayout_18.addWidget(self.bt_tableOff)
        self.verticalLayout_15.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_9.addLayout(self.verticalLayout_15)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_20.addWidget(self.label_27)
        self.horizontalLayout_7.addLayout(self.verticalLayout_20)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setMaximumSize(QtCore.QSize(210, 30))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_19.addWidget(self.label_23)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.bt_rightOn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_rightOn.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_rightOn.setObjectName("bt_rightOn")
        self.horizontalLayout_19.addWidget(self.bt_rightOn)
        self.bt_rightOff = QtWidgets.QPushButton(self.centralwidget)
        self.bt_rightOff.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_rightOff.setObjectName("bt_rightOff")
        self.horizontalLayout_19.addWidget(self.bt_rightOff)
        self.verticalLayout_19.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_7.addLayout(self.verticalLayout_19)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setMaximumSize(QtCore.QSize(210, 30))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_18.addWidget(self.label_24)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.bt_room3On = QtWidgets.QPushButton(self.centralwidget)
        self.bt_room3On.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_room3On.setObjectName("bt_room3On")
        self.horizontalLayout_20.addWidget(self.bt_room3On)
        self.bt_room3Off = QtWidgets.QPushButton(self.centralwidget)
        self.bt_room3Off.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_room3Off.setObjectName("bt_room3Off")
        self.horizontalLayout_20.addWidget(self.bt_room3Off)
        self.verticalLayout_18.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_7.addLayout(self.verticalLayout_18)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_23.addWidget(self.label_28)
        self.horizontalLayout_8.addLayout(self.verticalLayout_23)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setSpacing(2)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setMaximumSize(QtCore.QSize(210, 30))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_22.addWidget(self.label_25)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.bt_underOn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_underOn.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_underOn.setObjectName("bt_underOn")
        self.horizontalLayout_21.addWidget(self.bt_underOn)
        self.bt_underOff = QtWidgets.QPushButton(self.centralwidget)
        self.bt_underOff.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_underOff.setObjectName("bt_underOff")
        self.horizontalLayout_21.addWidget(self.bt_underOff)
        self.verticalLayout_22.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_8.addLayout(self.verticalLayout_22)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setMaximumSize(QtCore.QSize(210, 30))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_21.addWidget(self.label_26)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.bt_inputOn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_inputOn.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_inputOn.setObjectName("bt_inputOn")
        self.horizontalLayout_22.addWidget(self.bt_inputOn)
        self.bt_inputOff = QtWidgets.QPushButton(self.centralwidget)
        self.bt_inputOff.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_inputOff.setObjectName("bt_inputOff")
        self.horizontalLayout_22.addWidget(self.bt_inputOff)
        self.verticalLayout_21.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_8.addLayout(self.verticalLayout_21)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_30.setSpacing(10)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(230, 25))
        self.comboBox.setMaximumSize(QtCore.QSize(460, 50))
        self.comboBox.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_24.addWidget(self.comboBox)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.bt_play = QtWidgets.QPushButton(self.centralwidget)
        self.bt_play.setMinimumSize(QtCore.QSize(70, 25))
        self.bt_play.setMaximumSize(QtCore.QSize(140, 50))
        self.bt_play.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.bt_play.setObjectName("bt_play")
        self.horizontalLayout_23.addWidget(self.bt_play)
        self.bt_pause = QtWidgets.QPushButton(self.centralwidget)
        self.bt_pause.setMinimumSize(QtCore.QSize(70, 25))
        self.bt_pause.setMaximumSize(QtCore.QSize(140, 50))
        self.bt_pause.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.bt_pause.setObjectName("bt_pause")
        self.horizontalLayout_23.addWidget(self.bt_pause)
        self.bt_stop = QtWidgets.QPushButton(self.centralwidget)
        self.bt_stop.setMinimumSize(QtCore.QSize(70, 25))
        self.bt_stop.setMaximumSize(QtCore.QSize(140, 50))
        self.bt_stop.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.bt_stop.setObjectName("bt_stop")
        self.horizontalLayout_23.addWidget(self.bt_stop)
        self.verticalLayout_24.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_3.addLayout(self.verticalLayout_24)
        self.bt_alarm = QtWidgets.QPushButton(self.centralwidget)
        self.bt_alarm.setMinimumSize(QtCore.QSize(60, 55))
        self.bt_alarm.setMaximumSize(QtCore.QSize(120, 110))
        self.bt_alarm.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.bt_alarm.setObjectName("bt_alarm")
        self.horizontalLayout_3.addWidget(self.bt_alarm)
        self.slider = QtWidgets.QSlider(self.centralwidget)
        self.slider.setMinimumSize(QtCore.QSize(10, 55))
        self.slider.setMaximumSize(QtCore.QSize(20, 110))
        self.slider.setOrientation(QtCore.Qt.Vertical)
        self.slider.setObjectName("slider")
        self.horizontalLayout_3.addWidget(self.slider)
        self.verticalLayout_30.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.timer = QtWidgets.QLabel(self.centralwidget)
        self.timer.setMinimumSize(QtCore.QSize(230, 20))
        self.timer.setMaximumSize(QtCore.QSize(460, 40))
        self.timer.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";color: rgb(255, 255, 255);")
        self.timer.setTextFormat(QtCore.Qt.AutoText)
        self.timer.setAlignment(QtCore.Qt.AlignCenter)
        self.timer.setObjectName("timer")
        self.verticalLayout_25.addWidget(self.timer)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(230, 20))
        self.progressBar.setMaximumSize(QtCore.QSize(460, 40))
        self.progressBar.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";color: rgb(255, 255, 255);")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_25.addWidget(self.progressBar)
        self.horizontalLayout_2.addLayout(self.verticalLayout_25)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setMaximumSize(QtCore.QSize(162, 40))
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_26.addWidget(self.label_30)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.bt_m3min = QtWidgets.QPushButton(self.centralwidget)
        self.bt_m3min.setMinimumSize(QtCore.QSize(40, 20))
        self.bt_m3min.setMaximumSize(QtCore.QSize(80, 40))
        self.bt_m3min.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.bt_m3min.setObjectName("bt_m3min")
        self.horizontalLayout_24.addWidget(self.bt_m3min)
        self.bt_3min = QtWidgets.QPushButton(self.centralwidget)
        self.bt_3min.setMinimumSize(QtCore.QSize(40, 20))
        self.bt_3min.setMaximumSize(QtCore.QSize(80, 40))
        self.bt_3min.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.bt_3min.setObjectName("bt_3min")
        self.horizontalLayout_24.addWidget(self.bt_3min)
        self.verticalLayout_26.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_2.addLayout(self.verticalLayout_26)
        self.verticalLayout_30.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_30)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.connect_functions()
        self.stop_timer = True
        self.start_worker()


    def start_worker(self):
        self.thread = ThreadClass(parent=None)
        self.thread.start()
        self.thread.any_signal.connect(self.main_loop)

    def stop_worker(self):
        self.thread.stop()

    def main_loop(self):
        if _game.settings['questStatus'] == 4:
            self.stop_timer = True
            self.timer1.stop()
            self.bt_init.setEnabled(True)

        if _game.settings['initSensors']:
            print('initsensors')
            self.init_sensors()
        self.reset_sensors()
        self.reset_outs()

        if not _game.check() and not _game.settings['gameStatus'] and _game.settings['questStatus'] != 4:
            _game.settings['questStatus'] = 1
        elif _game.check() and not _game.settings['gameStatus'] and _game.settings['questStatus'] != 4:
            _game.settings['questStatus'] = 2

        if _game.outs['brick'] and _game.settings['brick_event']:
            _game.settings['brick_event'] = False
            threading.Thread(target=self.off_brick, daemon=True).start()

        if _game.settings['players_event']:
            _game.settings['players_event'] = False
            threading.Thread(target=self.play_5, daemon=True).start()
            threading.Thread(target=self.play_20, daemon=True).start()

        if _game.settings['startStatus']:
            _game.settings['startStatus'] = False
            _game.settings['gameStatus'] = not _game.settings['gameStatus']

            self.bt_init.setEnabled(False)
            if _game.settings['gameStatus']:
                _game.start_script()
                _game.settings['questStatus'] = 3
                self.timer1 = QTimer(self.centralwidget)
                self.timer1.timeout.connect(self.timer_run)
                self.timer1.start(1000)
            else:
                _game.settings['questStatus'] = 4
                self.stop_timer = True
                self.timer1.stop()

        self.change_quest_state_text()
        self.change_quest_state_color()
        self.reset_time()
        self.reset_progressbar()

    def off_brick(self):
        time.sleep(3)
        self.bt_brickOff_press()

    def play_5(self):
        time.sleep(5)
        _game.playersEvent_script(1)
    def play_20(self):
        time.sleep(20)
        _game.playersEvent_script(2)


    def red_sensor(self, sensor):
        pixmap = QPixmap("img/red.jpg")
        sensor.setPixmap(pixmap)
    def green_sensor(self, sensor):
        pixmap = QPixmap("img/green.jpg")
        sensor.setPixmap(pixmap)
    def red_out(self, out):
        out.setStyleSheet("background-color: rgb(255, 255, 255);")
    def green_out(self, out):
        out.setStyleSheet("background-color: rgb(0, 255, 0);")

    def init_sensors(self):
        if _game.inputs['runQuest']:
            self.green_sensor(self.runImg)
        else:
            self.red_sensor(self.runImg)

        if _game.inputs['doorRead']:
            self.green_sensor(self.doorImg)
        else:
            self.red_sensor(self.doorImg)

        if _game.inputs['bookRead']:
            self.green_sensor(self.bookImg)
        else:
            self.red_sensor(self.bookImg)

        if _game.inputs['coinRead']:
            self.green_sensor(self.coinImg)
        else:
            self.red_sensor(self.coinImg)

        if _game.inputs['declarationRead']:
            self.green_sensor(self.declarationImg)
        else:
            self.red_sensor(self.declarationImg)

        if _game.inputs['brickRead']:
            self.green_sensor(self.brickImg)
        else:
            self.red_sensor(self.brickImg)

        if _game.inputs['handRead']:
            self.green_sensor(self.handImg)
        else:
            self.red_sensor(self.handImg)

        if _game.inputs['cupRead']:
            self.green_sensor(self.cupImg)
        else:
            self.red_sensor(self.cupImg)

        if _game.inputs['tableRead']:
            self.green_sensor(self.tableImg)
        else:
            self.red_sensor(self.tableImg)

        if _game.inputs['presidentRead']:
            self.green_sensor(self.presidentImg)
        else:
            self.red_sensor(self.presidentImg)

        if _game.inputs['ringRead']:
            self.green_sensor(self.ringImg)
        else:
            self.red_sensor(self.ringImg)

        if _game.inputs['playersRead']:
            self.green_sensor(self.playersImg)
        else:
            self.red_sensor(self.playersImg)
        _game.settings['initSensors'] = False

    def reset_sensors(self):
        if _game.inputs['runQuest']:
            self.green_sensor(self.runImg)
        else:
            self.red_sensor(self.runImg)

        if _game.inputs['doorRead']:
            self.green_sensor(self.doorImg)
        else:
            self.red_sensor(self.doorImg)

        if _game.inputs['bookRead']:
            self.green_sensor(self.bookImg)

        if _game.inputs['coinRead']:
            self.green_sensor(self.coinImg)

        if _game.inputs['declarationRead']:
            self.green_sensor(self.declarationImg)

        if _game.inputs['brickRead']:
            self.green_sensor(self.brickImg)

        if _game.inputs['handRead']:
            self.green_sensor(self.handImg)

        if _game.inputs['cupRead']:
            self.green_sensor(self.cupImg)

        if _game.inputs['tableRead']:
            self.green_sensor(self.tableImg)

        if _game.inputs['presidentRead']:
            self.green_sensor(self.presidentImg)

        if _game.inputs['ringRead']:
            self.green_sensor(self.ringImg)

        if _game.inputs['playersRead']:
            self.green_sensor(self.playersImg)
        else:
            self.red_sensor(self.playersImg)

    def reset_outs(self):
        if _game.outs['hallway']:
            self.green_out(self.bt_hallwayOn)
        else:
            self.red_out(self.bt_hallwayOn)
        if _game.outs['room1']:
            self.green_out(self.bt_room1On)
        else:
            self.red_out(self.bt_room1On)
        if _game.outs['coin']:
            self.green_out(self.bt_coinOn)
        else:
            self.red_out(self.bt_coinOn)
        if _game.outs['declaration']:
            self.green_out(self.bt_declarationOn)
        else:
            self.red_out(self.bt_declarationOn)
        if _game.outs['brick']:
            self.green_out(self.bt_brickOn)
        else:
            self.red_out(self.bt_brickOn)
        if _game.outs['stones']:
            self.green_out(self.bt_stoneOn)
        else:
            self.red_out(self.bt_stoneOn)
        if _game.outs['room2']:
            self.green_out(self.bt_room2On)
        else:
            self.red_out(self.bt_room2On)
        if _game.outs['left']:
            self.green_out(self.bt_leftOn)
        else:
            self.red_out(self.bt_leftOn)
        if _game.outs['table']:
            self.green_out(self.bt_tableOn)
        else:
            self.red_out(self.bt_tableOn)
        if _game.outs['right']:
            self.green_out(self.bt_rightOn)
        else:
            self.red_out(self.bt_rightOn)
        if _game.outs['room3']:
            self.green_out(self.bt_room3On)
        else:
            self.red_out(self.bt_room3On)
        if _game.outs['under']:
            self.green_out(self.bt_underOn)
        else:
            self.red_out(self.bt_underOn)
        if _game.outs['input']:
            self.green_out(self.bt_inputOn)
        else:
            self.red_out(self.bt_inputOn)

    def change_quest_state_color(self):
        if _game.settings['questStatus'] == 1:
            self.quest_state.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        elif _game.settings['questStatus'] == 2:
            self.quest_state.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        elif _game.settings['questStatus'] == 3:
            self.quest_state.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        elif _game.settings['questStatus'] == 4:
            self.quest_state.setStyleSheet("background-color: rgb(66, 171, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")

    def change_quest_state_text(self):
        if _game.settings['questStatus'] == 1:
            self.quest_state.setText("Квест не собран")
        elif _game.settings['questStatus'] == 2:
            self.quest_state.setText("Квест собран")
        elif _game.settings['questStatus'] == 3:
            self.quest_state.setText("Квест запущен")
        elif _game.settings['questStatus'] == 4:
            self.quest_state.setText("Квест окончен")


    def connect_functions(self):
        self.bt_init.clicked.connect(self.bt_init_press)
        self.bt_run.clicked.connect(self.bt_run_press)

        self.bt_hallwayOn.clicked.connect(self.bt_hallwayOn_press)
        self.bt_hallwayOff.clicked.connect(self.bt_hallwayOff_press)  
        self.bt_room1On.clicked.connect(self.bt_room1On_press)
        self.bt_room1Off.clicked.connect(self.bt_room1Off_press) 
        self.bt_coinOn.clicked.connect(self.bt_coinOn_press)
        self.bt_coinOff.clicked.connect(self.bt_coinOff_press) 
        self.bt_declarationOn.clicked.connect(self.bt_declarationOn_press)
        self.bt_declarationOff.clicked.connect(self.bt_declarationOff_press) 
        self.bt_brickOn.clicked.connect(self.bt_brickOn_press)
        self.bt_brickOff.clicked.connect(self.bt_brickOff_press) 
        self.bt_stoneOn.clicked.connect(self.bt_stoneOn_press)
        self.bt_stoneOff.clicked.connect(self.bt_stoneOff_press) 
        self.bt_room2On.clicked.connect(self.bt_room2On_press)
        self.bt_room2Off.clicked.connect(self.bt_room2Off_press) 
        self.bt_leftOn.clicked.connect(self.bt_leftOn_press)
        self.bt_leftOff.clicked.connect(self.bt_leftOff_press) 
        self.bt_tableOn.clicked.connect(self.bt_tableOn_press)
        self.bt_tableOff.clicked.connect(self.bt_tableOff_press) 
        self.bt_rightOn.clicked.connect(self.bt_rightOn_press)
        self.bt_rightOff.clicked.connect(self.bt_rightOff_press) 
        self.bt_room3On.clicked.connect(self.bt_room3On_press)
        self.bt_room3Off.clicked.connect(self.bt_room3Off_press)
        self.bt_underOn.clicked.connect(self.bt_underOn_press)
        self.bt_underOff.clicked.connect(self.bt_underOff_press) 
        self.bt_inputOn.clicked.connect(self.bt_inputOn_press)
        self.bt_inputOff.clicked.connect(self.bt_inputOff_press)  

        self.bt_play.clicked.connect(self.bt_play_press)
        self.bt_pause.clicked.connect(self.bt_pause_press)
        self.bt_stop.clicked.connect(self.bt_stop_press)
        self.bt_alarm.clicked.connect(self.bt_alarm_press)
        self.slider.valueChanged.connect(self.change_volume)

        self.bt_3min.clicked.connect(self.bt_3min_press)
        self.bt_m3min.clicked.connect(self.bt_m3min_press)


    def bt_init_press(self):
        _time.time = 0
        _time.time_limit = 3600
        _game.settings['initSensors'] = True
        _game.settings['questStatus'] = 1
        self.reset_time()
        self.reset_progressbar()

    def bt_run_press(self):
        _game.settings['startStatus'] = True
        self.stop_timer = not self.stop_timer

    def bt_hallwayOn_press(self):
        self.bt_hallwayOn.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['hallway'] = True
        _game.reset_out('hallway')

    def bt_hallwayOff_press(self):
        self.bt_hallwayOn.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['hallway'] = False
        _game.reset_out('hallway')

    def bt_room1On_press(self):
        self.bt_room1On.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['room1'] = True
        _game.reset_out('room1')

    def bt_room1Off_press(self):
        self.bt_room1On.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['room1'] = False
        _game.reset_out('room1')

    def bt_coinOn_press(self):
        self.bt_coinOn.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['coin'] = True
        _game.reset_out('coin')

    def bt_coinOff_press(self):
        self.bt_coinOn.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['coin'] = False
        _game.reset_out('coin')

    def bt_declarationOn_press(self):
        self.bt_declarationOn.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['declaration'] = True
        _game.reset_out('declaration')

    def bt_declarationOff_press(self):
        self.bt_declarationOn.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['declaration'] = False
        _game.reset_out('declaration')

    def bt_brickOn_press(self):
        self.bt_brickOn.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['brick'] = True
        _game.reset_out('brick')
        _game.settings['brick_event'] = True

    def bt_brickOff_press(self):
        self.bt_brickOn.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['brick'] = False
        _game.reset_out('brick')

    def bt_stoneOn_press(self):
        self.bt_stoneOn.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['stones'] = True
        _game.reset_out('stones')

    def bt_stoneOff_press(self):
        self.bt_stoneOn.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['stones'] = False
        _game.reset_out('stones')

    def bt_room2On_press(self):
        self.bt_room2On.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['room2'] = True
        _game.reset_out('room2')

    def bt_room2Off_press(self):
        self.bt_room2On.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['room2'] = False
        _game.reset_out('room2')

    def bt_leftOn_press(self):
        self.bt_leftOn.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['left'] = True
        _game.reset_out('left')

    def bt_leftOff_press(self):
        self.bt_leftOn.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['left'] = False
        _game.reset_out('left')

    def bt_tableOn_press(self):
        self.bt_tableOn.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['table'] = True
        _game.reset_out('table')

    def bt_tableOff_press(self):
        self.bt_tableOn.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['table'] = False
        _game.reset_out('table')

    def bt_rightOn_press(self):
        self.bt_rightOn.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['right'] = True
        _game.reset_out('right')

    def bt_rightOff_press(self):
        self.bt_rightOn.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['right'] = False
        _game.reset_out('right')

    def bt_room3On_press(self):
        self.bt_room3On.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['room3'] = True
        _game.reset_out('room3')

    def bt_room3Off_press(self):
        self.bt_room3On.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['room3'] = False
        _game.reset_out('room3')

    def bt_underOn_press(self):
        self.bt_underOn.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['under'] = True
        _game.reset_out('under')

    def bt_underOff_press(self):
        self.bt_underOn.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['under'] = False
        _game.reset_out('under')

    def bt_inputOn_press(self):
        self.bt_inputOn.setStyleSheet("background-color: rgb(0, 255, 0);")
        _game.outs['input'] = True
        _game.reset_out('input')

    def bt_inputOff_press(self):
        self.bt_inputOn.setStyleSheet("background-color: rgb(255, 255, 255);") 
        _game.outs['input'] = False
        _game.reset_out('input')       

    def bt_play_press(self):
        _game.play_music(self.comboBox.currentText())

    def bt_pause_press(self):
        _game.pause_music(self.comboBox.currentText())

    def bt_stop_press(self):
        _game.stop_music(self.comboBox.currentText())

    def bt_alarm_press(self):
        _game.play_music('Трек №9  «Alarm»')

    def change_volume(self, value):
        if _game.settings['volume'] != value:
            _game.settings['volume'] = value
            _game.change_volume()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Массоны"))
        self.run.setText(_translate("MainWindow", "Запуск сценария / кнопка"))
        self.door.setText(_translate("MainWindow", "Геркона двери"))
        self.book.setText(_translate("MainWindow", "Книги"))
        self.coin.setText(_translate("MainWindow", "Монетница"))
        self.declaration.setText(_translate("MainWindow", "Кнопка декларации"))
        self.brick.setText(_translate("MainWindow", "Кнопка кирпича"))
        self.hand.setText(_translate("MainWindow", "Сканер руки"))
        self.cup.setText(_translate("MainWindow", "Кубок"))
        self.table.setText(_translate("MainWindow", "Ящик стола"))
        self.president.setText(_translate("MainWindow", "Президенты"))
        self.ring.setText(_translate("MainWindow", "Перстень"))
        self.players.setText(_translate("MainWindow", "Список участников"))
        self.bt_init.setText(_translate("MainWindow", "Init quest"))
        self.quest_state.setText(_translate("MainWindow", "Квест собран"))
        self.bt_run.setText(_translate("MainWindow", "Run quest"))
        self.label_15.setText(_translate("MainWindow", "Свет в коридоре"))
        self.bt_hallwayOn.setText(_translate("MainWindow", "On"))
        self.bt_hallwayOff.setText(_translate("MainWindow", "Off"))
        self.label_16.setText(_translate("MainWindow", "Свет в 1 комнате"))
        self.bt_room1On.setText(_translate("MainWindow", "On"))
        self.bt_room1Off.setText(_translate("MainWindow", "Off"))
        self.label_14.setText(_translate("MainWindow", "Шкатулка"))
        self.bt_coinOn.setText(_translate("MainWindow", "On"))
        self.bt_coinOff.setText(_translate("MainWindow", "Off"))
        self.label_17.setText(_translate("MainWindow", "Декларация"))
        self.bt_declarationOn.setText(_translate("MainWindow", "On"))
        self.bt_declarationOff.setText(_translate("MainWindow", "Off"))
        self.label_18.setText(_translate("MainWindow", "Подсветка кирпича"))
        self.bt_brickOn.setText(_translate("MainWindow", "On"))
        self.bt_brickOff.setText(_translate("MainWindow", "Off"))
        self.label_19.setText(_translate("MainWindow", "Камни/ниша"))
        self.bt_stoneOn.setText(_translate("MainWindow", "On"))
        self.bt_stoneOff.setText(_translate("MainWindow", "Off"))
        self.label_20.setText(_translate("MainWindow", "Проход во 2 комнату (свет)"))
        self.bt_room2On.setText(_translate("MainWindow", "On"))
        self.bt_room2Off.setText(_translate("MainWindow", "Off"))
        self.label_21.setText(_translate("MainWindow", "Левый ящик комода"))
        self.bt_leftOn.setText(_translate("MainWindow", "On"))
        self.bt_leftOff.setText(_translate("MainWindow", "Off"))
        self.label_22.setText(_translate("MainWindow", "Ящик стола"))
        self.bt_tableOn.setText(_translate("MainWindow", "On"))
        self.bt_tableOff.setText(_translate("MainWindow", "Off"))
        self.label_23.setText(_translate("MainWindow", "Правый ящик комода"))
        self.bt_rightOn.setText(_translate("MainWindow", "On"))
        self.bt_rightOff.setText(_translate("MainWindow", "Off"))
        self.label_24.setText(_translate("MainWindow", "Проход в 3 комнату"))
        self.bt_room3On.setText(_translate("MainWindow", "On"))
        self.bt_room3Off.setText(_translate("MainWindow", "Off"))
        self.label_25.setText(_translate("MainWindow", "Лаз"))
        self.bt_underOn.setText(_translate("MainWindow", "On"))
        self.bt_underOff.setText(_translate("MainWindow", "Off"))
        self.label_26.setText(_translate("MainWindow", "ЭМ входа"))
        self.bt_inputOn.setText(_translate("MainWindow", "On"))
        self.bt_inputOff.setText(_translate("MainWindow", "Off"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Трек №1  «Райли»"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Трек №2  «1-я комната»"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Трек №3  «2-я комната»"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Трек №4  «3-я комната»"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Трек №5  «Сигнализация»"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Трек №6  «Побег»"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Трек №7  «Победа»"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Трек №8  «Поражение»"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Трек №9  «Alarm»"))
        self.bt_play.setText(_translate("MainWindow", "Play"))
        self.bt_pause.setText(_translate("MainWindow", "Pause"))
        self.bt_stop.setText(_translate("MainWindow", "Stop"))
        self.bt_alarm.setText(_translate("MainWindow", "Alarm"))
        self.timer.setText(_translate("MainWindow", "Времени квеста прошло: 00:00:00 / 01:00:00"))
        self.bt_m3min.setText(_translate("MainWindow", "- 3 мин"))
        self.bt_3min.setText(_translate("MainWindow", "+ 3 мин"))


    def timer_run(self):
        _time.time += 1
        print(_time.time)

        if _time.time == _time.time_limit:
            self.stop_timer = True
            _game.settings['questStatus'] = 4
            _game.louse_script()
            self.timer1.stop()

    def reset_time(self):
        self.timer.setText(f'Времени квеста прошло: '+\
        f'{_time.get_hours(_time.time)}:{_time.get_minutes(_time.time)}:{_time.get_seconds(_time.time)} / '+\
        f'{_time.get_hours(_time.time_limit)}:{_time.get_minutes(_time.time_limit)}:{_time.get_seconds(_time.time_limit)}')

    def reset_progressbar(self):
        self.progressBar.setProperty("value", int(_time.time/_time.time_limit*100))

    def bt_m3min_press(self):
        if _time.time_limit > 3600:
            _time.time_limit -= 180
        self.reset_time()

    def bt_3min_press(self):
        _time.time_limit += 180
        self.reset_time()


stylesheet = """
    QMainWindow {
        background-image: url("img/background.jpeg"); 
        background-repeat: no-repeat; 
        background-position: center;
    }
"""

if __name__ == "__main__":
        import sys
        QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
        app = QtWidgets.QApplication(sys.argv)
        app.setStyleSheet(stylesheet)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
